// Generated by scripts/embed-migrations.ts — do not edit manually.
// Run "bun run embed:migrations" after adding new migrations.
import journalJson from "./migrations/meta/_journal.json" with { type: "json" };
import m0000 from "./migrations/0000_tidy_namor.sql" with { type: "text" };
import m0001 from "./migrations/0001_complete_starjammers.sql" with { type: "text" };
import m0002 from "./migrations/0002_sloppy_eternals.sql" with { type: "text" };
import m0003 from "./migrations/0003_studio_pages.sql" with { type: "text" };
import m0004 from "./migrations/0004_block_shapes.sql" with { type: "text" };
import m0005 from "./migrations/0005_block_text_style.sql" with { type: "text" };
import m0006 from "./migrations/0006_read_library.sql" with { type: "text" };
import m0007 from "./migrations/0007_series_hierarchy.sql" with { type: "text" };
import m0008 from "./migrations/0008_quiet_magus.sql" with { type: "text" };
import m0009 from "./migrations/0009_nervous_ultimates.sql" with { type: "text" };
import m0010 from "./migrations/0010_tan_marvel_zombies.sql" with { type: "text" };
import m0011 from "./migrations/0011_shallow_mandarin.sql" with { type: "text" };
import m0012 from "./migrations/0012_thankful_venom.sql" with { type: "text" };

const files: Record<string, string> = {
  "0000_tidy_namor.sql": m0000,
  "0001_complete_starjammers.sql": m0001,
  "0002_sloppy_eternals.sql": m0002,
  "0003_studio_pages.sql": m0003,
  "0004_block_shapes.sql": m0004,
  "0005_block_text_style.sql": m0005,
  "0006_read_library.sql": m0006,
  "0007_series_hierarchy.sql": m0007,
  "0008_quiet_magus.sql": m0008,
  "0009_nervous_ultimates.sql": m0009,
  "0010_tan_marvel_zombies.sql": m0010,
  "0011_shallow_mandarin.sql": m0011,
  "0012_thankful_venom.sql": m0012,
};

/** Embedded migration SQL keyed by filename, plus the raw journal JSON. */
export const embeddedMigrations = { journal: JSON.stringify(journalJson), files };

/** Number of migrations compiled into this binary. Zero means a packaging fault. */
export const embeddedMigrationCount: number = Object.keys(files).length;
