// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebOcrServer.Data;

#nullable disable

namespace WebOcrServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726032802_AddPageTranslationLog")]
    partial class AddPageTranslationLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("WebOcrServer.Data.OcrLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OcrLogs");
                });

            modelBuilder.Entity("WebOcrServer.Data.PageTranslationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BubbleH")
                        .HasColumnType("REAL");

                    b.Property<int>("BubbleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float>("BubbleW")
                        .HasColumnType("REAL");

                    b.Property<float>("BubbleX")
                        .HasColumnType("REAL");

                    b.Property<float>("BubbleY")
                        .HasColumnType("REAL");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PageTranslationLogs");
                });

            modelBuilder.Entity("WebOcrServer.Data.TranslateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranslateLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
